### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [355]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
file_to_load = "purchase_data.txt"

# Read Purchasing File and store into Pandas data frame
df = pd.read_csv('purchase_data.csv', delimiter = ',')
df

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44
5,5,Yalae81,22,Male,81,Dreamkiss,3.61
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67
8,8,Undjask33,22,Male,21,Souleater,1.10
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89
16,16,Lisirra25,20,Male,40,Second Chance,2.52
17,17,Zontibe81,21,Male,161,Devine,1.76
18,18,Reunasu60,22,Female,82,Nirvana,4.90
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81
23,23,Eyrian71,40,Male,151,Severance,3.40
24,24,Siala43,30,Male,141,Persuasion,3.19
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
26,26,Lirtossa84,11,Male,71,Demise,1.61
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16
...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15
756,756,Ilast79,20,Male,73,Ritual Mace,2.05
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60
758,758,Iral74,21,Male,182,Toothpick,4.03
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70
762,762,Asur53,26,Male,110,Suspension,1.44
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07
765,765,Irith83,18,Male,130,Alpha,2.07
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14
767,767,Ilmol66,8,Female,92,Final Critic,4.88
768,768,Assassasta79,38,Male,92,Final Critic,4.88
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58
770,770,Lirtosia63,34,Male,12,Dawne,1.02
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02
774,774,Jiskjask80,11,Male,101,Final Critic,4.19
775,775,Aethedru70,21,Female,60,Wolf,3.54
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46
778,778,Sisur91,7,Male,101,Final Critic,4.19
779,779,Ennrian78,24,Male,50,Dawn,4.60

## Player Count

* Display the total number of players

In [356]:
df.nunique()

Purchase ID    780
SN             576
Age             39
Gender           3
Item ID        183
Item Name      179
Price          145
dtype: int64

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [357]:
print(df['SN'].nunique())
print(df['Price'].mean())
print(df['Purchase ID'].count())
print(df['Price'].sum())

576
3.050987179487176
780
2379.77

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [358]:
print(df['Gender'].str.contains('Male').value_counts())
print(df['Gender'].str.contains('Male').value_counts(normalize=True)*100)
print(df['Gender'].str.contains('Female').value_counts())
print(df['Gender'].str.contains('Female').value_counts(normalize=True)*100)
print(df['Gender'].str.contains('Other/Non-disclosed').value_counts())
print(df['Gender'].str.contains('Other/Non-disclosed').value_counts(normalize=True)*100)

True     652
False    128
Name: Gender, dtype: int64
True     83.589744
False    16.410256
Name: Gender, dtype: float64
False    667
True     113
Name: Gender, dtype: int64
False    85.512821
True     14.487179
Name: Gender, dtype: float64
False    780
Name: Gender, dtype: int64
False    100.0
Name: Gender, dtype: float64


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [359]:
print(df.groupby('Gender')['Purchase ID'].count())
print(df.groupby('Gender')['Price'].mean())
print(df.groupby('Gender')['Price'].sum())
print(df.groupby('Gender')['Price'].mean())

Gender
Female                   113
Male                     652
Other / Non-Disclosed     15
Name: Purchase ID, dtype: int64
Gender
Female                   3.203009
Male                     3.017853
Other / Non-Disclosed    3.346000
Name: Price, dtype: float64
Gender
Female                    361.94
Male                     1967.64
Other / Non-Disclosed      50.19
Name: Price, dtype: float64
Gender
Female                   3.203009
Male                     3.017853
Other / Non-Disclosed    3.346000
Name: Price, dtype: float64

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [360]:
bins = [0,9,14,19,24,29,34,39,100]
labels = ['<10','10-14','15-19','20-24','25-29','30-34','35-39','40-100']

df['Age_Demographics'] = pd.cut(df["Age"], bins, labels=labels)
df = df.groupby("Age_Demographics")

total_count_age = df["Age"].nunique()
full_sum_players = df["Age"].sum()
age_demographics_df=pd.DataFrame(total_count_age)
percent_of_players = total_count_age / full_sum_players

age_demographics_df['Total Count Age'] = total_count_age
age_demographics_df2 = pd.DataFrame(age_demographics_df)
age_demographics_df2['Percent of Players'] = percent_of_players
age_demographics_df3 = pd.DataFrame(age_demographics_df2)
(age_demographics_df3)
# df = df.groupby("player_summary")
# total_players_value = df["SN"].count()
# total_count_player = df["SN"].sum()
# percentage_of_players = total_count_player/total_players_value

                  Age  Total Count Age  Percent of Players
Age_Demographics
<10                 3                3            0.016575
10-14               5                5            0.015674
15-19               5                5            0.002189
20-24               5                5            0.000627
25-29               5                5            0.001904
30-34               5                5            0.002182
35-39               5                5            0.003322
40-100              6                6            0.011111

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [361]:
bins = [0,9,14,19,24,29,34,39,100]
labels = ['<10','10-14','15-19','20-24','25-29','30-34','35-39','40-100']

df["Age_summary"] = pd.cut(df["Age"], bins, labels=labels)
df = df.groupby("Age_summary")
total_count_age = df["Purchase ID"].count()
age_purchase_df=pd.DataFrame(total_count_age)
avg_purchase_price_age = df ["Price"].mean()
total_purchase_value = df["Price"].sum()
total_count_age = df["SN"].nunique()
avg_purchase_per_person_age = total_purchase_value/total_count_age

age_purchase_df['Average Purchase Price'] = avg_purchase_price_age
age_purchase_df2 = pd.DataFrame(age_purchase_df)
age_purchase_df2['Total Purchase Value'] = total_purchase_value
age_purchase_df3 = pd.DataFrame(age_purchase_df2)
age_purchase_df3['Avg Total Purchase per Person'] = avg_purchase_per_person_age
age_purchase_df4 = pd.DataFrame(age_purchase_df3)
(age_purchase_df4)

ValueError: setting an array element with a sequence

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [362]:
bins = [0,9,14,19,24,29,34,39,100]
labels = ['<10','10-14','15-19','20-24','25-29','30-34','35-39','40-100']

df["top_spenders"] = pd.cut(df["Price"],bins,labels=labels)

max_purchase_count = df['Price'].max()
avg_purchase_price = df['Price'].mean()
total_purchase_price = df['Price'].sum()
top_spenders_df=pd.DataFrame(max_purchase_count)

top_spenders_df['Max Purchase Price'] = max_purchase_price
top_spenders_df2 = pd.DataFrame(top_spenders_df)
top_spenders_df2['Average Purchase Price'] = avg_purchase_price
top_spenders_df3 = pd.DataFrame(top_spenders_df2)
top_spenders_df3['Total Purchase Price'] = total_purchase_price
top_spenders_df4 = pd.DataFrame(top_spenders_df3)
(top_spenders_df4)

ValueError: setting an array element with a sequence

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [368]:
# print(df["Item_ID"] = df('Purchase ID'))
# print(df["Item_Name"] = df['Item Name'])
# df["Purchase_Count"] = df['Purchase ID'].count()
# df["Item_Price"] = df['Price'].sum()
# df["Total_Purchase_Value"] = df["Item_ID"] + df["Purchase_Count"]

print(df.groupby('Item ID')['Item Name'].count('Purchase ID'))
print(df.groupby('Item ID')['Item Name'].mean('Item Price'))
print(df.groupby('Item ID')['Item Name'].sum('Item Price'))

AttributeError: Cannot access callable attribute 'groupby' of 'DataFrameGroupBy' objects, try using the 'apply' method

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

,,Purchase Count,Item Price,Total Purchase Value
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,$4.23,$50.76
82,Nirvana,9,$4.90,$44.10
145,Fiery Glass Crusader,9,$4.58,$41.22
92,Final Critic,8,$4.88,$39.04
103,Singed Scalpel,8,$4.35,$34.80